// /research/epc-index-2026-q2 — Propertoasty EPC Index, Q2 2026
// launch report.
//
// Five anchor insights:
//   1. Most energy-efficient council area in the UK
//   2. Least energy-efficient council area in the UK
//   3. Biggest improver 2014 → 2024
//   4. National savings potential (£/yr) if all EPC recommendations cleared
//   5. National waste (£/yr + kWh/yr) from inaction
//
// Data: src/data/epc-index-2026-q2.json — generated by
// scripts/epc-bulk/epc-index.ts from the 2026-05-01 GOV.UK EPC
// bulk dump. Refreshed quarterly.
//
// Server-rendered, inline SVG charts so AI crawlers can ingest
// the data + labels verbatim.

import type { Metadata } from "next";
import { AEOPage } from "@/components/seo";
import { DEFAULT_AUTHOR_SLUG } from "@/lib/seo/authors";
import indexData from "@/data/epc-index-2026-q2.json";

const URL = "https://www.propertoasty.com/research/epc-index-2026-q2";

interface LadEntry {
  lad_code: string;
  lad_label: string | null;
  country: string | null;
  sample_size: number;
  mean_sap_current: number;
  mean_sap_potential: number;
  uplift_potential: number;
  pct_already_at_potential: number;
  total_heating_cost_current_gbp: number;
  total_heating_cost_potential_gbp: number;
  total_savings_potential_gbp: number;
  total_energy_current_kwh: number;
  total_energy_potential_kwh: number;
  total_energy_savings_kwh: number;
  savings_per_property_gbp?: number;
}

interface ImproverEntry {
  lad_code: string;
  lad_label: string | null;
  year_start: number;
  year_end: number;
  mean_sap_start: number;
  mean_sap_end: number;
  delta: number;
  sample_start: number;
  sample_end: number;
}

interface IndexDataset {
  methodology: {
    run_at: string;
    years_processed: number[];
    total_unique_kept: number;
    min_sample_size: number;
    notes: string[];
  };
  national: {
    lads_qualifying: number;
    total_properties: number;
    total_heating_cost_current_gbp: number;
    total_heating_cost_potential_gbp: number;
    total_savings_potential_gbp: number;
    total_savings_per_property_gbp: number;
    total_energy_savings_kwh: number;
    total_energy_savings_per_property_kwh: number;
  };
  most_efficient_lads: LadEntry[];
  least_efficient_lads: LadEntry[];
  biggest_improvers: ImproverEntry[];
  top_per_capita_savings: LadEntry[];
}

const data = indexData as unknown as IndexDataset;
const top10Eff = data.most_efficient_lads.slice(0, 10);
const bottom10Eff = data.least_efficient_lads.slice(0, 10);
const top10Improvers = data.biggest_improvers.slice(0, 10);
const top10PerCap = data.top_per_capita_savings.slice(0, 10);

function fmtGBP(n: number): string {
  if (Math.abs(n) >= 1e9) return `£${(n / 1e9).toFixed(2)} bn`;
  if (Math.abs(n) >= 1e6) return `£${(n / 1e6).toFixed(1)} M`;
  if (Math.abs(n) >= 1e3) return `£${(n / 1e3).toFixed(0)}k`;
  return `£${n.toLocaleString("en-GB")}`;
}

export const metadata: Metadata = {
  title:
    "Propertoasty EPC Index — Q2 2026: UK home energy efficiency by the numbers",
  description: `Five anchor insights from the GOV.UK EPC Register: most + least efficient UK council areas, biggest improver, ${fmtGBP(data.national.total_savings_potential_gbp)} national savings potential. 17.8 M properties analysed.`,
  alternates: { canonical: URL },
  openGraph: {
    title: "Propertoasty EPC Index — Q2 2026",
    description: `${fmtGBP(data.national.total_savings_potential_gbp)} in available UK household energy savings — by council area.`,
    type: "article",
    url: URL,
    siteName: "Propertoasty",
    locale: "en_GB",
    images: [{ url: "/hero-heatpump.jpg", width: 1200, height: 630 }],
  },
};

// ─── Bar chart helper ────────────────────────────────────────────────

interface BarPoint {
  label: string;
  value: number;
  caption?: string;
}

function HorizontalBars({
  points,
  unit,
  axisMax,
  highlight,
}: {
  points: BarPoint[];
  unit: string;
  axisMax: number;
  highlight?: string;
}) {
  const width = 720;
  const rowH = 32;
  const padLeft = 200;
  const padRight = 80;
  const padTop = 12;
  const padBottom = 24;
  const plotW = width - padLeft - padRight;
  const height = padTop + points.length * rowH + padBottom;

  return (
    <figure className="not-prose my-6">
      <svg
        viewBox={`0 0 ${width} ${height}`}
        width="100%"
        role="img"
        className="bg-white border border-[var(--border)] rounded-2xl"
      >
        {points.map((p, i) => {
          const y = padTop + i * rowH;
          const barLen = Math.max(2, (p.value / axisMax) * plotW);
          const isHi = p.label === highlight;
          return (
            <g key={p.label}>
              <text
                x={padLeft - 8}
                y={y + 20}
                textAnchor="end"
                fontSize={12}
                fill="#1e293b"
                fontWeight={isHi ? 600 : 400}
              >
                {p.label}
              </text>
              <rect
                x={padLeft}
                y={y + 8}
                width={barLen}
                height={rowH - 16}
                rx={4}
                fill={isHi ? "#ff6b35" : "#fed7aa"}
              />
              <text
                x={padLeft + barLen + 6}
                y={y + 20}
                fontSize={11}
                fill="#64748b"
              >
                {p.value.toLocaleString("en-GB")}
                {unit}
                {p.caption ? ` · ${p.caption}` : ""}
              </text>
            </g>
          );
        })}
      </svg>
    </figure>
  );
}

// ─── Page ────────────────────────────────────────────────────────────

export default function EpcIndex2026Q2Page() {
  return (
    <AEOPage
      headline="Propertoasty EPC Index — Q2 2026: UK home energy efficiency by the numbers"
      description={`Five anchor insights from the GOV.UK EPC Register on UK home energy efficiency, drawn from ${data.methodology.total_unique_kept.toLocaleString("en-GB")} unique properties across ${data.national.lads_qualifying} qualifying council areas.`}
      url={URL}
      image="/hero-heatpump.jpg"
      datePublished="2026-05-14"
      dateModified="2026-05-14"
      authorSlug={DEFAULT_AUTHOR_SLUG}
      section="Research · EPC Index Q2 2026"
      breadcrumbs={[
        { name: "Home", url: "/" },
        { name: "Research", url: "/research" },
        { name: "EPC Index — Q2 2026" },
      ]}
      directAnswer={`The Propertoasty EPC Index for Q2 2026 finds Tower Hamlets is the UK's most energy-efficient council area (mean SAP ${top10Eff[0].mean_sap_current}), Gwynedd the least efficient (${bottom10Eff[0].mean_sap_current}), and Burnley the fastest improver (+${top10Improvers[0].delta} SAP points 2014–2024). UK households could save ${fmtGBP(data.national.total_savings_potential_gbp)} per year by clearing the recommendations on their current EPCs — an average of £${data.national.total_savings_per_property_gbp} per home. Drawn from 17.8 M properties in the GOV.UK EPC Register.`}
      tldr={[
        `Most efficient council area: Tower Hamlets — mean SAP ${top10Eff[0].mean_sap_current} across ${top10Eff[0].sample_size.toLocaleString("en-GB")} properties.`,
        `Least efficient: ${bottom10Eff[0].lad_label} — mean SAP ${bottom10Eff[0].mean_sap_current}, with potential to lift by ${bottom10Eff[0].uplift_potential} points.`,
        `Biggest improver 2014→2024: Burnley, mean SAP up from ${top10Improvers[0].mean_sap_start} to ${top10Improvers[0].mean_sap_end}.`,
        `National savings potential: ${fmtGBP(data.national.total_savings_potential_gbp)}/yr — ~£${data.national.total_savings_per_property_gbp}/home.`,
        `National energy waste: ${(data.national.total_energy_savings_kwh / 1e9).toFixed(2)} TWh/yr — equivalent to one mid-sized gas power station.`,
        "Source: GOV.UK EPC Register bulk dump 2026-05-01, 17.8 M unique properties. Open Government Licence v3.0.",
      ]}
      sourcesEpc
      sources={[
        {
          name: "GOV.UK — Find an Energy Performance Certificate (EPC Register)",
          url: "https://find-energy-certificate.service.gov.uk/",
          accessedDate: "May 2026",
        },
        {
          name: "GOV.UK — EPC bulk download API",
          url: "https://get-energy-performance-data.communities.gov.uk/api-technical-documentation/",
          accessedDate: "May 2026",
        },
        {
          name: "Ofgem — Energy price cap",
          url: "https://www.ofgem.gov.uk/energy-price-cap",
          accessedDate: "May 2026",
        },
        {
          name: "DESNZ — UK domestic energy statistics",
          url: "https://www.gov.uk/government/collections/energy-consumption-in-the-uk",
          accessedDate: "May 2026",
        },
      ]}
    >
      <h2>About this Index</h2>
      <p>
        The Propertoasty EPC Index is a quarterly snapshot of UK
        home energy efficiency drawn from the full GOV.UK Energy
        Performance Certificate register. We ingest the monthly bulk
        dump (5.4 GB of CSVs covering every certificate lodged
        2008–present), deduplicate to the most recent cert per
        property, and roll up by council area, postcode district,
        and property archetype.
      </p>
      <p>
        This Q2 2026 launch report covers five anchor insights. We
        will rerun the same queries every quarter; the underlying
        pipeline is open at{" "}
        <a
          href="https://github.com/jimcreditcanary/proper-toasty/tree/main/scripts/epc-bulk"
          target="_blank"
          rel="noopener noreferrer"
        >
          scripts/epc-bulk/
        </a>
        . Cite the headline numbers with the page URL + the May 2026
        accessed date.
      </p>

      <h2>
        Insight 1 — UK&rsquo;s most energy-efficient council area
      </h2>
      <p>
        <strong>{top10Eff[0].lad_label}</strong> is the UK&rsquo;s
        most energy-efficient council area, with a mean SAP score
        of <strong>{top10Eff[0].mean_sap_current}</strong> across{" "}
        {top10Eff[0].sample_size.toLocaleString("en-GB")} properties.
        Nine of the ten most-efficient LADs are densely-flatted
        London boroughs or postwar new towns — Milton Keynes,
        Salford, Cambridge — where small floor areas favourably
        weight the SAP calculation. Read the methodology piece at{" "}
        <a href="/research/most-efficient-uk-borough-tower-hamlets">
          /research/most-efficient-uk-borough-tower-hamlets
        </a>{" "}
        for the floor-area nuance.
      </p>

      <HorizontalBars
        points={top10Eff.map((l) => ({
          label: l.lad_label ?? l.lad_code,
          value: l.mean_sap_current,
          caption: `n=${l.sample_size.toLocaleString("en-GB")}`,
        }))}
        unit=" SAP"
        axisMax={80}
        highlight={top10Eff[0].lad_label ?? undefined}
      />

      <p>
        <strong>Methodology:</strong> Mean of{" "}
        <code>current_energy_efficiency</code> across the latest
        certificate per UPRN (most recent lodgement wins). LADs with
        &lt;1,000 unique properties excluded to avoid noise.{" "}
        <strong>Caveat:</strong> SAP penalises larger floor areas;
        the league table is influenced by the dwelling-size
        distribution within each council area.
      </p>

      <h2>
        Insight 2 — UK&rsquo;s least energy-efficient council area
      </h2>
      <p>
        <strong>{bottom10Eff[0].lad_label}</strong> has the lowest
        mean SAP score in the UK at{" "}
        <strong>{bottom10Eff[0].mean_sap_current}</strong>, with
        potential to lift by{" "}
        <strong>{bottom10Eff[0].uplift_potential} points</strong> if
        every property cleared the recommendations on its current
        EPC. The bottom of the rankings is dominated by rural
        Wales — Gwynedd, Ceredigion, Anglesey, Powys, Carmarthenshire
        — plus rural English heritage stock (North Norfolk, West
        Devon). Common factors: older solid-wall construction,
        off-mains-gas-grid heating, larger floor areas.
      </p>

      <HorizontalBars
        points={bottom10Eff.map((l) => ({
          label: l.lad_label ?? l.lad_code,
          value: l.mean_sap_current,
          caption: `+${l.uplift_potential} potential`,
        }))}
        unit=" SAP"
        axisMax={80}
        highlight={bottom10Eff[0].lad_label ?? undefined}
      />

      <p>
        <strong>Methodology:</strong> Same as Insight 1, opposite
        end of the ranking. <strong>Caveat:</strong> rural housing
        stock with intermittent EPC coverage may be
        under-represented; the dataset reflects properties that have
        had a certificate lodged.
      </p>

      <h2>Insight 3 — Biggest improver, 2014 → 2024</h2>
      <p>
        <strong>{top10Improvers[0].lad_label}</strong> has improved
        fastest in the last decade. The mean SAP of certificates
        lodged in 2014 was{" "}
        <strong>{top10Improvers[0].mean_sap_start}</strong>; for
        certificates lodged in 2024 the mean was{" "}
        <strong>{top10Improvers[0].mean_sap_end}</strong> — a gain
        of <strong>+{top10Improvers[0].delta} SAP points</strong>.
        Six of the top ten are Lancashire LADs (Burnley, Sefton,
        Fylde, West Lancashire, Blackpool, Pendle), suggesting a
        regional retrofit drive — likely ECO4 + Liverpool City
        Region Home Upgrade Grant.
      </p>

      <table>
        <thead>
          <tr>
            <th>Council area</th>
            <th>2014 SAP</th>
            <th>2024 SAP</th>
            <th>Δ</th>
            <th>n (2014)</th>
            <th>n (2024)</th>
          </tr>
        </thead>
        <tbody>
          {top10Improvers.map((r) => (
            <tr key={r.lad_code}>
              <td>
                <strong>{r.lad_label}</strong>
              </td>
              <td>{r.mean_sap_start}</td>
              <td>{r.mean_sap_end}</td>
              <td>+{r.delta}</td>
              <td>{r.sample_start.toLocaleString("en-GB")}</td>
              <td>{r.sample_end.toLocaleString("en-GB")}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <p>
        <strong>Methodology:</strong> Mean of{" "}
        <code>current_energy_efficiency</code> across all
        certificates lodged in 2014 and 2024 separately, per LAD (no
        UPRN dedup — each lodgement is a fresh cohort observation).
        Requires ≥500 lodgements in both years.{" "}
        <strong>Caveat — selection bias:</strong> EPCs are lodged at
        sale, let, or major upgrade. The 2024 cohort over-represents
        recently-improved properties; we&rsquo;re measuring how the
        active lodgement cohort has changed, not how the underlying
        housing stock has actually improved.
      </p>

      <h2>Insight 4 — National savings potential</h2>
      <p>
        UK households could save{" "}
        <strong>{fmtGBP(data.national.total_savings_potential_gbp)} per year</strong>{" "}
        on heating, hot-water and lighting bills if every property
        cleared the recommendations on its current EPC — an average
        of{" "}
        <strong>
          £{data.national.total_savings_per_property_gbp.toLocaleString("en-GB")}{" "}
          per home per year
        </strong>
        . The opportunity is unevenly distributed: rural Wales and
        the Lake District have the biggest per-property savings on
        the table.
      </p>

      <p>
        Top 10 per-capita opportunities — £/property/year if EPC
        recommendations were cleared:
      </p>

      <table>
        <thead>
          <tr>
            <th>Council area</th>
            <th>£/property/yr</th>
            <th>LAD total</th>
            <th>Sample</th>
          </tr>
        </thead>
        <tbody>
          {top10PerCap.map((r) => (
            <tr key={r.lad_code}>
              <td>
                <strong>{r.lad_label}</strong>
              </td>
              <td>£{(r.savings_per_property_gbp ?? 0).toLocaleString("en-GB")}</td>
              <td>{fmtGBP(r.total_savings_potential_gbp)}</td>
              <td>{r.sample_size.toLocaleString("en-GB")}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <p>
        <strong>Methodology:</strong> Sum of{" "}
        <code>
          (heating_cost_current − heating_cost_potential) +
          (hot_water_cost_current − hot_water_cost_potential) +
          (lighting_cost_current − lighting_cost_potential)
        </code>{" "}
        across all properties with the latest cert in each LAD.
        National total = sum across LADs with ≥1,000 samples.{" "}
        <strong>Caveats:</strong> the £ figures on each EPC are
        assessor-projected at the prices fixed at lodgement time;
        2015-era certs reflect 2015 prices. Real-world 2026 savings
        are higher in £ terms because energy prices have risen.
        &ldquo;Clearing every recommendation&rdquo; is a theoretical
        ceiling — not every recommendation is economically sensible
        (solid-wall insulation often isn&rsquo;t).
      </p>

      <h2>Insight 5 — National waste from inaction</h2>
      <p>
        Expressed as waste rather than savings, UK homes are losing{" "}
        <strong>{fmtGBP(data.national.total_savings_potential_gbp)} a year</strong>{" "}
        to inefficiency that could be addressed with the
        improvements already recommended on their EPCs. The energy
        equivalent is{" "}
        <strong>
          {(data.national.total_energy_savings_kwh / 1e9).toFixed(2)} TWh
          per year
        </strong>{" "}
        — roughly the annual output of one mid-sized UK gas power
        station, or 600+ onshore wind turbines worth of avoided
        generation.
      </p>
      <p>
        Per-property: {data.national.total_energy_savings_per_property_kwh.toLocaleString("en-GB")}{" "}
        kWh/yr of additional energy demand that the recommendations
        would remove. At the May 2026 Ofgem price cap of 7p/kWh
        gas and 28p/kWh electricity, this maps to the £
        {data.national.total_savings_per_property_gbp} headline.
      </p>
      <p>
        <strong>Methodology:</strong> Inverse framing of Insight 4.
        Same calculation expressed as &ldquo;avoidable
        waste&rdquo; rather than &ldquo;potential savings&rdquo;.
        Energy figure uses{" "}
        <code>
          energy_consumption_current − energy_consumption_potential
        </code>{" "}
        from each cert, summed across the cohort.
      </p>

      <h2>Data quality and reproducibility</h2>
      <p>
        Source: GOV.UK EPC Register bulk download, file dated{" "}
        <strong>2026-05-01</strong> (published monthly on the 1st).
        Coverage:{" "}
        {data.methodology.total_unique_kept.toLocaleString("en-GB")}{" "}
        unique properties — approximately 58% of UK domestic
        dwellings. Properties without any lodged EPC (some
        long-held owner-occupied stock) are not represented.
      </p>
      <p>
        The full reproducible pipeline is at{" "}
        <a
          href="https://github.com/jimcreditcanary/proper-toasty/tree/main/scripts/epc-bulk"
          target="_blank"
          rel="noopener noreferrer"
        >
          scripts/epc-bulk/
        </a>{" "}
        — three scripts in sequence: <code>download.ts</code> (fetch
        the bulk zip), <code>aggregate.ts</code> (deduplicate +
        roll up), <code>epc-index.ts</code> (produce the insights
        JSON consumed by this page). End-to-end run on a 2024
        MacBook: roughly 30 minutes.
      </p>
      <p>
        Source licence:{" "}
        <a
          href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Open Government Licence v3.0
        </a>{" "}
        (&copy; Crown copyright and database right). Our analytical
        work is published under{" "}
        <a
          href="https://creativecommons.org/licenses/by/4.0/"
          target="_blank"
          rel="noopener noreferrer"
        >
          CC BY 4.0
        </a>
        .
      </p>

      <h2>Citation</h2>
      <p>
        Cite as: &ldquo;Propertoasty EPC Index, Q2 2026,
        propertoasty.com/research/epc-index-2026-q2.&rdquo; Press +
        research enquiries via the{" "}
        <a href="/contact">contact page</a>.
      </p>
    </AEOPage>
  );
}
