// Pillar rotation + topic picker for the weekly blog generator
// (/api/cron/blog-generator).
//
// Design goals:
//   - Steady coverage across pillars, no clustering.
//   - Never repeat a topic within a 90-day window.
//   - Blog corpus grows by ~4 posts/month; each is genuinely useful
//     UK 2026 content, not filler.

import type { SupabaseClient } from "@supabase/supabase-js";

export type BlogPillar =
  | "heat_pump"
  | "solar"
  | "plug_in_solar"
  | "boiler_vs_hp";

// Weekly rotation. UTC ISO week number modulo 4 → pillar. This is
// deterministic across restarts + doesn't depend on how many runs
// have happened. If we ever add a 5th pillar, extend the modulus
// without breaking the sequence.
const ROTATION: BlogPillar[] = [
  "heat_pump",
  "solar",
  "plug_in_solar",
  "boiler_vs_hp",
];

export function pillarForWeek(d: Date): BlogPillar {
  const week = isoWeek(d);
  return ROTATION[week % ROTATION.length];
}

// ISO 8601 week number — Thursday-anchored, Monday-start. Good
// enough for pillar rotation; not exposed publicly, so no need
// for the full date-fns weight.
function isoWeek(d: Date): number {
  const target = new Date(
    Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()),
  );
  const dayNr = (target.getUTCDay() + 6) % 7;
  target.setUTCDate(target.getUTCDate() - dayNr + 3);
  const firstThursday = target.getTime();
  target.setUTCMonth(0, 1);
  if (target.getUTCDay() !== 4) {
    target.setUTCMonth(0, 1 + ((4 - target.getUTCDay() + 7) % 7));
  }
  return (
    1 +
    Math.ceil((firstThursday - target.getTime()) / (7 * 24 * 3600 * 1000))
  );
}

export interface ExistingPost {
  slug: string;
  title: string;
  category: string;
  published_at: string | null;
}

/**
 * Recent posts we should avoid re-covering. Callers pass the
 * result into the writer's system prompt so the model steers away
 * from topics we've already published.
 */
export async function loadRecentPostsForPillar(
  pillar: BlogPillar,
  supabase: SupabaseClient,
  windowDays = 90,
): Promise<ExistingPost[]> {
  const cutoff = new Date(
    Date.now() - windowDays * 24 * 60 * 60 * 1000,
  ).toISOString();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data } = await (supabase as any)
    .from("blog_posts")
    .select("slug, title, category, published_at")
    .eq("published", true)
    .gte("published_at", cutoff)
    .order("published_at", { ascending: false })
    .limit(30);
  const rows = (data ?? []) as ExistingPost[];
  return rows.filter((r) => matchesPillar(r, pillar));
}

/**
 * Also load the last 6 posts generated by the auto-generator on this
 * pillar, so we don't loop through the same 3-4 angles quarter after
 * quarter. Reads blog_gen_runs (migration 083), not blog_posts, so a
 * rejection still counts as "we tried this angle".
 */
export async function loadRecentGenTopics(
  pillar: BlogPillar,
  supabase: SupabaseClient,
  limit = 6,
): Promise<string[]> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data } = await (supabase as any)
    .from("blog_gen_runs")
    .select("topic")
    .eq("pillar", pillar)
    .order("created_at", { ascending: false })
    .limit(limit);
  return ((data ?? []) as Array<{ topic: string }>).map((r) => r.topic);
}

// Pillar → categoriser. Blog posts have loose category strings
// ("Guides", "News", "Installer Voices"); we route by title +
// category + slug like the social agent does.
function matchesPillar(post: ExistingPost, pillar: BlogPillar): boolean {
  const hay =
    `${post.slug} ${post.title} ${post.category}`.toLowerCase();
  switch (pillar) {
    case "plug_in_solar":
      return (
        hay.includes("plug-in-solar") ||
        hay.includes("plug in solar") ||
        hay.includes("balcony solar")
      );
    case "heat_pump":
      return (
        hay.includes("heat-pump") ||
        hay.includes("heat pump") ||
        hay.includes("bus grant") ||
        hay.includes("boiler upgrade") ||
        hay.includes("air source") ||
        hay.includes("ground source")
      );
    case "solar":
      return (
        hay.includes("solar") ||
        hay.includes(" pv ") ||
        hay.includes("smart export") ||
        hay.includes("battery")
      );
    case "boiler_vs_hp":
      return (
        hay.includes("boiler ban") ||
        hay.includes("gas boiler") ||
        (hay.includes("boiler") && hay.includes("heat pump"))
      );
  }
}

/**
 * Human label — used in the runbook + cron log line.
 */
export function pillarLabel(p: BlogPillar): string {
  switch (p) {
    case "heat_pump":
      return "Heat pumps (myths, running costs, BUS grant)";
    case "solar":
      return "Solar + battery (payback, SEG, roof suitability)";
    case "plug_in_solar":
      return "Plug-in solar (renters, flats, BS 7671 A4)";
    case "boiler_vs_hp":
      return "Boiler vs heat pump (cost, policy, replacement decisions)";
  }
}
