-- Human-readable short IDs for checks.
--
-- Why: support staff want a 6-char ID they can quote on a phone call.
-- The uuid is fine for URLs but unusable for "what's the report ID
-- on your screen?".
--
-- Alphabet: Crockford base32 — 0-9 + A-Z minus I/L/O/U:
--   - I vs 1, O vs 0 confusion when read aloud or hand-written
--   - L vs 1 confusion in some fonts
--   - U because we don't want accidental rude four-char substrings
-- That leaves 32 characters, 32^6 ≈ 1.07B combinations. Plenty for
-- our volumes; if we ever blow through it the column type stays text
-- so we can widen to 7 chars without a migration.
--
-- Generation: a plpgsql function loops with random selection until
-- it finds an unused value. The unique index on the column is the
-- correctness backstop — even if two transactions race, the second
-- one's INSERT fails the constraint, the trigger retries.
--
-- Backfill: every existing checks row gets one. Done in a single
-- statement using a recursive CTE seeded by gen_random_bytes — slow
-- per row but the table is small (single-digit thousands at most),
-- so this finishes in well under a second on prod.

create or replace function public.gen_check_short_id()
returns text
language plpgsql
volatile
as $$
declare
  -- 32 unambiguous chars (digits 0-9 plus A-Z minus I/L/O/U).
  alphabet constant text := '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
  result text;
  i int;
  candidate text;
  exists_count int;
begin
  loop
    candidate := '';
    for i in 1..6 loop
      -- Pick a random char from the alphabet. floor(random() * 32) is
      -- inclusive 0..31 — perfect for substr's 1-indexed offset.
      candidate := candidate || substr(alphabet, 1 + floor(random() * 32)::int, 1);
    end loop;
    -- Probe for collision. The unique index is the hard backstop;
    -- this just keeps the trigger from failing the INSERT in the
    -- 1-in-half-a-billion case.
    select count(*) into exists_count
      from public.checks
      where short_id = candidate;
    if exists_count = 0 then
      result := candidate;
      exit;
    end if;
  end loop;
  return result;
end;
$$;

comment on function public.gen_check_short_id is
  '6-char Crockford-style base32 ID, collision-checked. Used as the BEFORE INSERT trigger source on public.checks.short_id.';

-- ─── Column ─────────────────────────────────────────────────────────
alter table public.checks
  add column if not exists short_id text;

-- Backfill before the not-null + unique constraint go on. Each row
-- gets its own generated ID. The function loops on collision so this
-- is safe to run with concurrent inserts (though there shouldn't be
-- any during a migration).
do $$
declare
  r record;
begin
  for r in select id from public.checks where short_id is null loop
    update public.checks
       set short_id = public.gen_check_short_id()
     where id = r.id;
  end loop;
end $$;

-- Now the unique index + not null can land cleanly.
create unique index if not exists checks_short_id_unique
  on public.checks (short_id);

alter table public.checks
  alter column short_id set not null;

comment on column public.checks.short_id is
  '6-char human-readable ID (Crockford base32 minus I/L/O/U) for support + admin search. Generated by trigger on insert.';

-- ─── Trigger ────────────────────────────────────────────────────────
create or replace function public.set_check_short_id()
returns trigger
language plpgsql
as $$
begin
  if new.short_id is null then
    new.short_id := public.gen_check_short_id();
  end if;
  return new;
end;
$$;

drop trigger if exists checks_set_short_id on public.checks;
create trigger checks_set_short_id
  before insert on public.checks
  for each row execute function public.set_check_short_id();

-- ─── Reload PostgREST schema ────────────────────────────────────────
notify pgrst, 'reload schema';
